# -*- coding: utf-8 -*-
"""Lista_de_exercicios_python

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/157JuDQ6DwSk12x6pC0-FXOFra9Pzk25r
"""

print("Números Pares e Ímpares de 0 a 100:")
for i in range(101):
    if i % 2 == 0:
        print(f"{i} é PAR")
    else:
        print(f"{i} é ÍMPAR")

numeros = []
for i in range(3):
    valor = float(input("Digite um número: "))
    numeros.append(valor)

print("O maior valor digitado foi:", max(numeros))
print("O menor valor digitado foi:", min(numeros))

nome = input("Digite seu nome: ")
for i in range(len(nome) + 1):
    print(nome[:i].upper())

n = int(input("Deseja ver a sequência até qual termo? "))
t1 = 1
t2 = 1
print(f"{t1}, {t2}", end="")
cont = 3
while cont <= n:
    t3 = t1 + t2
    print(f", {t3}", end="")
    t1 = t2
    t2 = t3
    cont += 1
print("... Fim.")

nome = input("Digite o nome: ")
while len(nome) <= 3:
    nome = input("Nome muito curto! Digite novamente: ")

idade = int(input("Digite a idade: "))
while idade < 0 or idade > 150:
    idade = int(input("Idade inválida! Digite entre 0 e 150: "))

salario = float(input("Digite o salário: "))
while salario <= 0:
    salario = float(input("Salário deve ser maior que zero: "))

sexo = input("Sexo (f/m): ").lower()
while sexo != 'f' and sexo != 'm':
    sexo = input("Incorreto. Digite f ou m: ")

estado_civil = input("Estado civil (s, c, v, d): ").lower()
while estado_civil not in ['s', 'c', 'v', 'd']:
    estado_civil = input("Erro. Digite s, c, v ou d: ")

print("Cadastro validado!")

num = int(input("Digite um número: "))
divisores = 0

for i in range(1, num + 1):
    if num % i == 0:
        divisores = divisores + 1

if divisores == 2:
    print("O número é primo")
else:
    print("Não é primo")

n = int(input("Calcular o fatorial de: "))
f = 1
for i in range(n, 0, -1):
    f *= i
print(f"O resultado do fatorial é: {f}")

L = [5, 7, 2, 9, 4, 1, 3]

print("Tamanho da lista:", len(L))
print("Maior valor:", max(L))
print("Menor valor:", min(L))
print("Soma de tudo:", sum(L))

L.sort()
print("Ordem crescente:", L)

L.reverse()
print("Ordem decrescente:", L)

tabela = {
    "linha1": {"item": "Sensor", "valor": "Temperatura"},
    "linha2": {"item": "Status", "valor": "Ativo"},
    "linha3": {"item": "Local", "valor": "Estufa 01"}
}
print(tabela)

senha_correta = "676767"
tentativa = ""

while tentativa != senha_correta:
    tentativa = input("Digite a senha: ")
    if tentativa != senha_correta:
        print("Senha incorreta! Tente de novo.")

print("Acesso liberado")

num = int(input("Você Quer a tabuada de qual número (1 a 10)? "))

if num >= 1 and num <= 10:
    for i in range(1, 11):
        print(f"{num} x {i} = {num * i}")
else:
    print("Número fora do intervalo!")